FROM ghcr.io/cloudbase/garm:nightly@sha256:716b40dfa91aa59f405fd39b3688890106263596fd438846018a5e13a8819594 AS release
ARG rev
COPY build/$rev/linux/amd64/garm-provider-harvester /opt/garm/providers.d/garm-provider-harvester
RUN chmod 755 /opt/garm/providers.d/garm-provider-harvester

ENTRYPOINT ["/bin/garm", "-config", "/etc/garm/config.toml"]