FROM ghcr.io/cloudbase/garm:nightly@sha256:acd527ab90448e1b72b639b201ace7af27e8fcb49384c094dadd1aa6e1ac4f58 AS release
ARG rev
COPY build/$rev/linux/amd64/garm-provider-harvester /opt/garm/providers.d/garm-provider-harvester
RUN chmod 755 /opt/garm/providers.d/garm-provider-harvester

ENTRYPOINT ["/bin/garm", "-config", "/etc/garm/config.toml"]